module.exports = {
  apps: [
    {
      name: "alpaka-server",
      script: "node_modules/.bin/next",
      args: "start",
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      watch: false,
      max_memory_restart: "4G",
      max_restarts: 15,
      min_uptime: "5s",
      restart_delay: 2000,
      exp_backoff_restart_delay: 100,
      kill_timeout: 5000,
      listen_timeout: 10000,
      env: {
        NODE_ENV: "production",
        PORT: "3000"
      },
      error_file: "./logs/alpaka-server-error.log",
      out_file: "./logs/alpaka-server-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z"
    },
    {
      name: "Психодиагностика",
      script: "workers/trigger-worker.ts",
      interpreter: "node",
      interpreter_args: "--require ts-node/register",
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      watch: false,
      max_memory_restart: "4G",
      max_restarts: 15,
      min_uptime: "5s",
      restart_delay: 2000,
      exp_backoff_restart_delay: 100,
      kill_timeout: 5700000,
      listen_timeout: 10000,
      env: {
        NODE_ENV: "production",
        TS_NODE_PROJECT: "workers/tsconfig.json",
        ALPAKA_STANDALONE_MODE: "true",
        ENABLE_FILE_LOGGING: "true",
        PROJECT_ID: "cmivy6xz50140vtb10mfgqpdq",
        PROJECT_NAME: "Психодиагностика",
        MODE_FILTER: "PSYCHODIAGNOSTICS",
        POLL_INTERVAL: "10000",
        MAX_CONCURRENT_JOBS: "5",
        ALPAKA_SECRET: "8aZppqg26k4/+7PETzaN1BVoabnZXFGShdoCyJTKJsc=",
        ALPAKA_INTERNAL_SECRET: "8aZppqg26k4/+7PETzaN1BVoabnZXFGShdoCyJTKJsc=",
        EXTERNAL_API_BASE_URL: "http://localhost:4000",
        INTERNAL_API_BASE_URL: "http://localhost:3000",
        DATABASE_URL: "postgresql://psypro_user:psypro_password@localhost:5433/psypro_db"
      },
      error_file: "./logs/psychodiagnostika-error.log",
      out_file: "./logs/psychodiagnostika-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z"
    },
    {
      name: "Профориентация",
      script: "workers/trigger-worker.ts",
      interpreter: "node",
      interpreter_args: "--require ts-node/register",
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      watch: false,
      max_memory_restart: "4G",
      max_restarts: 15,
      min_uptime: "5s",
      restart_delay: 2000,
      exp_backoff_restart_delay: 100,
      kill_timeout: 5700000,
      listen_timeout: 10000,
      env: {
        NODE_ENV: "production",
        TS_NODE_PROJECT: "workers/tsconfig.json",
        ALPAKA_STANDALONE_MODE: "true",
        ENABLE_FILE_LOGGING: "true",
        PROJECT_ID: "cmivy7e4y01mjvtb1oudlrgzj",
        PROJECT_NAME: "Профориентация",
        MODE_FILTER: "CAREER_GUIDANCE",
        POLL_INTERVAL: "10000",
        MAX_CONCURRENT_JOBS: "5",
        ALPAKA_SECRET: "8aZppqg26k4/+7PETzaN1BVoabnZXFGShdoCyJTKJsc=",
        ALPAKA_INTERNAL_SECRET: "8aZppqg26k4/+7PETzaN1BVoabnZXFGShdoCyJTKJsc=",
        EXTERNAL_API_BASE_URL: "http://localhost:4000",
        INTERNAL_API_BASE_URL: "http://localhost:3000",
        DATABASE_URL: "postgresql://psypro_user:psypro_password@localhost:5433/psypro_db"
      },
      error_file: "./logs/proforientacija-error.log",
      out_file: "./logs/proforientacija-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z"
    }
  ]
};
