import { jsPDF } from "jspdf";
import { addRussianFont } from "./roboto-font";
import { PDF } from "@/config/constants";

interface GeneratePDFOptions {
  title: string;
  content: string;
  reportType: "FULL" | "ADAPTED" | "SCORE_TABLE";
  respondentName?: string;
  date?: string;
}

export function generateReportPDF(options: GeneratePDFOptions): Blob {
  const { title, content, reportType, respondentName, date } = options;

  // Content is already plain text (parsed in SessionDetails), just clean escaped chars
  const cleanContent = content
    .replace(/\\n/g, "\n")
    .replace(/\*\*([^*]+)\*\*/g, "$1")
    .replace(/\*([^*]+)\*/g, "$1");

  // Create new PDF document with UTF-8 support
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
    putOnlyUsedFonts: true,
    compress: true,
  });

  // Add Russian font support
  addRussianFont(doc);

  // Colors
  const primaryColor =
    reportType === "FULL"
      ? PDF.COLOR.REPORT_FULL
      : reportType === "ADAPTED"
        ? PDF.COLOR.REPORT_ADAPTED
        : PDF.COLOR.REPORT_SCORE_TABLE;

  // Header
  doc.setFillColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.rect(0, 0, PDF.PAGE.WIDTH, 40, "F");

  // Logo/Brand text
  doc.setTextColor(PDF.COLOR.WHITE[0], PDF.COLOR.WHITE[1], PDF.COLOR.WHITE[2]);
  doc.setFontSize(24);
  doc.setFont("Roboto", "bold");
  const titleText = "Psy&Pro UI";
  doc.text(titleText, PDF.MARGIN.LEFT, PDF.MARGIN.TOP);

  // Report type badge
  doc.setFontSize(PDF.FONT_SIZE.BODY);
  doc.setFont("Roboto", "normal");
  const typeLabels = {
    FULL: "Full Report",
    ADAPTED: "Adapted Report",
    SCORE_TABLE: "Score Table",
  };
  doc.text(typeLabels[reportType], PDF.MARGIN.LEFT, 30);

  // Date
  if (date) {
    doc.text(date, PDF.PAGE.USABLE_WIDTH, 30);
  }

  // Reset text color
  doc.setTextColor(PDF.COLOR.BLACK[0], PDF.COLOR.BLACK[1], PDF.COLOR.BLACK[2]);

  // Title
  doc.setFontSize(PDF.FONT_SIZE.TITLE);
  doc.setFont("Roboto", "bold");
  doc.text(title, PDF.MARGIN.LEFT, 55);

  // Respondent name if provided
  if (respondentName) {
    doc.setFontSize(PDF.FONT_SIZE.SUBHEADING);
    doc.setFont("Roboto", "normal");
    doc.text(`Respondent: ${respondentName}`, PDF.MARGIN.LEFT, 65);
  }

  // Content
  doc.setFontSize(11);
  doc.setFont("Roboto", "normal");

  // Split content into lines that fit the page width
  const pageWidth = PDF.PAGE.USABLE_WIDTH;
  const lineHeight = PDF.LINE_HEIGHT.DEFAULT;
  let yPosition = respondentName ? 75 : 65;

  // Split content by newlines first
  const paragraphs = cleanContent.split("\n");

  paragraphs.forEach((paragraph) => {
    if (paragraph.trim() === "") {
      yPosition += lineHeight / 2;
      return;
    }

    // Word wrap for long paragraphs with UTF-8 support
    const lines = doc.splitTextToSize(paragraph, pageWidth);

    lines.forEach((line: string) => {
      // Check if we need a new page
      if (yPosition > PDF.PAGE.BREAK_THRESHOLD) {
        doc.addPage();
        yPosition = PDF.MARGIN.TOP;
      }

      // Use text method with UTF-8 encoding
      doc.text(line, PDF.MARGIN.LEFT, yPosition, { maxWidth: pageWidth });
      yPosition += lineHeight;
    });

    // Add small gap between paragraphs
    yPosition += lineHeight / 2;
  });

  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(PDF.FONT_SIZE.SMALL + 1);
    doc.setTextColor(
      PDF.COLOR.GRAY_128[0],
      PDF.COLOR.GRAY_128[1],
      PDF.COLOR.GRAY_128[2],
    );
    doc.text(`Page ${i} of ${pageCount}`, PDF.PAGE.WIDTH / 2, 287, {
      align: "center",
    });
    doc.text("Generated by Psy&Pro UI", PDF.PAGE.WIDTH / 2, 292, {
      align: "center",
    });
  }

  // Convert to blob
  return doc.output("blob");
}

export function downloadPDF(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
